// SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Commercial
//
// Homenvis — LBM-based indoor airflow simulation.
// Copyright (c) 2026 Haocheng Wen / AllinSim. All rights reserved.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public
// License along with this program.  If not, see
// <https://www.gnu.org/licenses/>.
//
// Commercial licenses are available. Contact AllinSim for details.

/**
 * 样本间：预设房间布局，供用户一键载入后直接开展计算。
 *
 * 存放方式选择"写在代码里"而非服务器 JSON：
 *  - 布局数据仅几 KB~几十 KB，随构建打包进前端 bundle，零服务器开销；
 *  - 纯前端，刷新即用，无网络请求，适合轻量化服务器；
 *  - 开源后用户可直接在此文件贡献新样本，透明可读。
 *
 * 每个样本是一个返回 RoomLayout 的工厂函数（而非静态对象），这样每次载入
 * 都通过 genId() 生成全新 ID，避免同一布局多次载入时 ID 冲突。
 */

import { type RoomLayout, genId, createDefaultSwing } from './room-layout';

/** 样板大类：用于弹窗中的分类筛选。新增样本时请归入合适大类。 */
export type SampleCategory = 'residential' | 'office' | 'commercial';

export const SAMPLE_CATEGORY_LABELS: Record<SampleCategory, string> = {
  residential: '住宅',
  office: '办公',
  commercial: '商业',
};

export interface SampleRoom {
  id: string;
  name: string;
  category: SampleCategory;  // 大类（住宅/办公/商业），供筛选
  description: string;       // 一句话工况说明
  tags: string[];            // 场景标签（如 扫风/自然对流/机械通风）
  emoji: string;             // 卡片图标
  build: () => RoomLayout;
}

/* ============================================================
 * 样本：简约客厅 · 空调+电视
 * 小型客厅，壁挂空调送风 + 液晶电视热源
 * 房间 ：residential
 * ============================================================ */
function simpleRoomRoom(): RoomLayout {
  return {
      length: 5,
      width: 5,
      height: 2.5,
      boxes: [
        {
            id: genId(),
            name: 'L型转角沙发',
            x: 1.3525048817289973,
            y: 3.4000000000000004,
            z: 0,
            L: 2.4,
            W: 1.6,
            H: 0.85,
            color: '#7a5a38',
            shape: 'box',
            doorHoles: [],
            rotZ: 3.141592653589793,
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 2.4,
                  W: 0.9,
                  H: 0.12,
                  shape: 'box',
                  color: '#5e4428',
                },
              {
                  x: 0.04,
                  y: 0.04,
                  z: 0.42,
                  L: 2.32,
                  W: 0.8200000000000001,
                  H: 0.14,
                  shape: 'box',
                  color: '#9a724a',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.42,
                  L: 2.4,
                  W: 0.18,
                  H: 0.43,
                  shape: 'box',
                  color: '#6e5232',
                },
              {
                  x: 0,
                  y: 0.78,
                  z: 0,
                  L: 0.9,
                  W: 0.8200000000000001,
                  H: 0.12,
                  shape: 'box',
                  color: '#5e4428',
                },
              {
                  x: 0.04,
                  y: 0.9,
                  z: 0.42,
                  L: 0.8200000000000001,
                  W: 0.66,
                  H: 0.14,
                  shape: 'box',
                  color: '#9a724a',
                },
              {
                  x: 2.2399999999999998,
                  y: 0,
                  z: 0,
                  L: 0.16,
                  W: 0.9,
                  H: 0.85,
                  shape: 'box',
                  color: '#5e4428',
                },
            ],
          },
        {
            id: genId(),
            name: '窗户',
            x: 4.175,
            y: 2.39959121838639,
            z: 0.6663658214996994,
            L: 1.6,
            W: 0.05,
            H: 1.4,
            color: '#7dd3fc',
            shape: 'box',
            doorHoles: [],
            rotZ: 1.5707963267948966,
            category: 'wall',
            isWindow: true,
            asHeatSource: true,
            windowTemp: 35,
          },
        {
            id: genId(),
            name: '低电视柜',
            x: 1.5143460177793777,
            y: 0,
            z: 0,
            L: 1.8,
            W: 0.4,
            H: 0.36,
            color: '#524236',
            shape: 'box',
            doorHoles: [],
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 1.8,
                  W: 0.4,
                  H: 0.025,
                  shape: 'box',
                  color: '#3e3228',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.33499999999999996,
                  L: 1.8,
                  W: 0.4,
                  H: 0.025,
                  shape: 'box',
                  color: '#5a4636',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.025,
                  L: 0.025,
                  W: 0.4,
                  H: 0.31,
                  shape: 'box',
                  color: '#3e3228',
                },
              {
                  x: 1.7750000000000001,
                  y: 0,
                  z: 0.025,
                  L: 0.025,
                  W: 0.4,
                  H: 0.31,
                  shape: 'box',
                  color: '#3e3228',
                },
              {
                  x: 0.025,
                  y: 0.375,
                  z: 0.025,
                  L: 1.75,
                  W: 0.025,
                  H: 0.31,
                  shape: 'box',
                  color: '#3e3228',
                },
              {
                  x: 0.04,
                  y: 0.04,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.12,
                  shape: 'box',
                  color: '#2e251d',
                },
              {
                  x: 1.71,
                  y: 0.04,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.12,
                  shape: 'box',
                  color: '#2e251d',
                },
              {
                  x: 0.04,
                  y: 0.31000000000000005,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.12,
                  shape: 'box',
                  color: '#2e251d',
                },
              {
                  x: 1.71,
                  y: 0.31000000000000005,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.12,
                  shape: 'box',
                  color: '#2e251d',
                },
              {
                  x: 0.6,
                  y: 0.025,
                  z: 0.145,
                  L: 0.02,
                  W: 0.35000000000000003,
                  H: 0.19,
                  shape: 'box',
                  color: '#3e3228',
                },
              {
                  x: 1.2,
                  y: 0.025,
                  z: 0.145,
                  L: 0.02,
                  W: 0.35000000000000003,
                  H: 0.19,
                  shape: 'box',
                  color: '#3e3228',
                },
            ],
          },
        {
            id: genId(),
            name: '茶几',
            x: 1.4707623218564543,
            y: 3,
            z: 0,
            L: 1,
            W: 0.5,
            H: 0.4,
            color: '#8b4513',
            shape: 'box',
            doorHoles: [],
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0.365,
                  L: 1,
                  W: 0.5,
                  H: 0.035,
                  shape: 'box',
                  color: '#6b3410',
                },
              {
                  x: 0.05,
                  y: 0.05,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.365,
                  shape: 'box',
                  color: '#6b3410',
                },
              {
                  x: 0.8999999999999999,
                  y: 0.05,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.365,
                  shape: 'box',
                  color: '#6b3410',
                },
              {
                  x: 0.05,
                  y: 0.4,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.365,
                  shape: 'box',
                  color: '#6b3410',
                },
              {
                  x: 0.8999999999999999,
                  y: 0.4,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.365,
                  shape: 'box',
                  color: '#6b3410',
                },
            ],
          },
      ],
      vents: [],
      heatSources: [],
      devices: [
        {
            id: genId(),
            deviceId: 'tv-75inch',
            name: '液晶电视 75寸',
            brand: 'TCL',
            category: 'tv',
            position: {
              x: 1.6000487045354745,
              y: 0.14767354123391013,
              z: 0.3967696410316694,
            },
            geometry: {
              length: 1.67,
              width: 0.09,
              height: 0.96,
            },
            bodyParts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 1.67,
                  W: 0.09,
                  H: 0.96,
                  shape: 'box',
                  color: '#0f172a',
                },
              {
                  x: 0.025,
                  y: 0,
                  z: 0.025,
                  L: 1.6199999999999999,
                  W: 0.09,
                  H: 0.9099999999999999,
                  shape: 'box',
                  color: '#111827',
                },
              {
                  x: 0.22,
                  y: 0,
                  z: -0.04,
                  L: 0.25,
                  W: 0.1,
                  H: 0.04,
                  shape: 'box',
                  color: '#334155',
                },
              {
                  x: 1.2,
                  y: 0,
                  z: -0.04,
                  L: 0.25,
                  W: 0.1,
                  H: 0.04,
                  shape: 'box',
                  color: '#334155',
                },
            ],
            modeIndex: 0,
            outlets: [],
            inlets: [],
            heatSourceId: 'item_5764',
            heatTemp: 35,
            color: '#1e293b',
          },
        {
            id: genId(),
            deviceId: 'ac-wall-gree-1.5hp',
            name: '壁挂式空调 1.5匹',
            brand: '格力',
            category: 'air_conditioner',
            position: {
              x: 2.0195854161222457,
              y: 4.699999999999999,
              z: 2.0300548597517643,
            },
            geometry: {
              length: 0.85,
              width: 0.3,
              height: 0.28,
            },
            bodyParts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.85,
                  W: 0.3,
                  H: 0.28,
                  shape: 'box',
                  color: '#e2e8f0',
                },
              {
                  x: 0,
                  y: 0.26,
                  z: 0.02,
                  L: 0.85,
                  W: 0.04,
                  H: 0.24000000000000002,
                  shape: 'box',
                  color: '#cbd5e1',
                },
              {
                  x: 0.02,
                  y: 0.24,
                  z: 0,
                  L: 0.8099999999999999,
                  W: 0.06,
                  H: 0.05,
                  shape: 'box',
                  color: '#94a3b8',
                },
            ],
            modeIndex: 0,
            outlets: [
              {
                  id: genId(),
                  name: '出风口',
                  relativePosition: [
                    0.425,
                    0.02,
                    0.02,
                  ],
                  size: [
                    0.6,
                    0.04,
                    0.04,
                  ],
                  velocity: [
                    0,
                    -2.25,
                    -0.625,
                  ],
                  temperature: 16,
                  swing: {
                    enabled: true,
                    mode: 'vertical',
                    amplitude: 0.5235987755982988,
                    period: 10,
                  },
                },
            ],
            inlets: [
              {
                  id: genId(),
                  name: '回风口',
                  relativePosition: [
                    0.425,
                    0.15,
                    0.27,
                  ],
                  size: [
                    0.5,
                    0.2,
                    0.02,
                  ],
                  mode: 'velocity',
                  velocity: [
                    0,
                    0,
                    -0.6,
                  ],
                  temperature: 25,
                },
            ],
            color: '#60a5fa',
          },
      ],
    };
}

/* ============================================================
 * 样本：实景户型 · 客厅+厨房
 * 真实户型：多台空调 + 油烟机排烟 + 吸顶换气扇
 * 房间 ：residential
 * ============================================================ */
function realRoomRoom(): RoomLayout {
  return {
      length: 10,
      width: 6,
      height: 2.5,
      boxes: [
        {
            id: genId(),
            name: '新墙体',
            x: 7,
            y: 0,
            z: 0,
            L: 3,
            W: 2,
            H: 2.5,
            color: '#94a3b8',
            shape: 'box',
            doorHoles: [],
            category: 'wall',
          },
        {
            id: genId(),
            name: '新墙体',
            x: 0,
            y: 1.85,
            z: 0,
            L: 7,
            W: 0.15,
            H: 2.5,
            color: '#94a3b8',
            shape: 'box',
            doorHoles: [
              {
                  id: genId(),
                  name: '门洞',
                  wallFace: 'south',
                  offsetFromLeft: 3.95,
                  width: 0.9,
                  height: 2,
                  sillHeight: 0,
                  open: true,
                },
            ],
            category: 'wall',
          },
        {
            id: genId(),
            name: '新墙体',
            x: 4,
            y: 0.925,
            z: 0,
            L: 2,
            W: 0.15,
            H: 2.5,
            color: '#94a3b8',
            shape: 'box',
            doorHoles: [
              {
                  id: genId(),
                  name: '门洞',
                  wallFace: 'south',
                  offsetFromLeft: 0.2,
                  width: 0.9,
                  height: 2,
                  sillHeight: 0,
                  open: true,
                },
            ],
            rotZ: 1.5707963267948966,
            category: 'wall',
          },
        {
            id: genId(),
            name: '新墙体',
            x: 1.75,
            y: 3.925,
            z: 0,
            L: 4,
            W: 0.15,
            H: 2.5,
            color: '#94a3b8',
            shape: 'box',
            doorHoles: [
              {
                  id: genId(),
                  name: '门洞',
                  wallFace: 'south',
                  offsetFromLeft: 2.5,
                  width: 0.9,
                  height: 2,
                  sillHeight: 0,
                  open: true,
                },
            ],
            rotZ: 1.5707963267948966,
            category: 'wall',
          },
        {
            id: genId(),
            name: '新墙体',
            x: 5.5,
            y: 3.925,
            z: 0,
            L: 4,
            W: 0.15,
            H: 2.5,
            color: '#94a3b8',
            shape: 'box',
            doorHoles: [
              {
                  id: genId(),
                  name: '门洞',
                  wallFace: 'south',
                  offsetFromLeft: 2.45,
                  width: 1.15,
                  height: 2,
                  sillHeight: 0,
                  open: true,
                },
            ],
            rotZ: 1.5707963267948966,
            category: 'wall',
          },
        {
            id: genId(),
            name: 'L型转角沙发',
            x: 3.4432537050252554,
            y: 4,
            z: 0,
            L: 2.4,
            W: 1.6,
            H: 0.85,
            color: '#7a5a38',
            shape: 'box',
            doorHoles: [],
            rotZ: 1.5707963267948966,
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 2.4,
                  W: 0.9,
                  H: 0.12,
                  shape: 'box',
                  color: '#5e4428',
                },
              {
                  x: 0.04,
                  y: 0.04,
                  z: 0.42,
                  L: 2.32,
                  W: 0.8200000000000001,
                  H: 0.14,
                  shape: 'box',
                  color: '#9a724a',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.42,
                  L: 2.4,
                  W: 0.18,
                  H: 0.43,
                  shape: 'box',
                  color: '#6e5232',
                },
              {
                  x: 0,
                  y: 0.78,
                  z: 0,
                  L: 0.9,
                  W: 0.8200000000000001,
                  H: 0.12,
                  shape: 'box',
                  color: '#5e4428',
                },
              {
                  x: 0.04,
                  y: 0.9,
                  z: 0.42,
                  L: 0.8200000000000001,
                  W: 0.66,
                  H: 0.14,
                  shape: 'box',
                  color: '#9a724a',
                },
              {
                  x: 2.2399999999999998,
                  y: 0,
                  z: 0,
                  L: 0.16,
                  W: 0.9,
                  H: 0.85,
                  shape: 'box',
                  color: '#5e4428',
                },
            ],
          },
        {
            id: genId(),
            name: '餐桌',
            x: 8.9,
            y: 4.8999999999999995,
            z: 0,
            L: 1.4,
            W: 0.8,
            H: 0.75,
            color: '#a0522d',
            shape: 'box',
            doorHoles: [],
            rotZ: 1.5707963267948966,
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0.71,
                  L: 1.4,
                  W: 0.8,
                  H: 0.04,
                  shape: 'box',
                  color: '#7a3e1f',
                },
              {
                  x: 0.06,
                  y: 0.06,
                  z: 0,
                  L: 0.06,
                  W: 0.06,
                  H: 0.71,
                  shape: 'box',
                  color: '#5e2f17',
                },
              {
                  x: 1.2799999999999998,
                  y: 0.06,
                  z: 0,
                  L: 0.06,
                  W: 0.06,
                  H: 0.71,
                  shape: 'box',
                  color: '#5e2f17',
                },
              {
                  x: 0.06,
                  y: 0.6799999999999999,
                  z: 0,
                  L: 0.06,
                  W: 0.06,
                  H: 0.71,
                  shape: 'box',
                  color: '#5e2f17',
                },
              {
                  x: 1.2799999999999998,
                  y: 0.6799999999999999,
                  z: 0,
                  L: 0.06,
                  W: 0.06,
                  H: 0.71,
                  shape: 'box',
                  color: '#5e2f17',
                },
            ],
          },
        {
            id: genId(),
            name: '双人床 1.8m',
            x: 1.28117486025937,
            y: 4.1,
            z: 0,
            L: 2,
            W: 1.8,
            H: 0.6,
            color: '#c9a96e',
            shape: 'box',
            doorHoles: [],
            rotZ: 1.5707963267948966,
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 2,
                  W: 1.8,
                  H: 0.18,
                  shape: 'box',
                  color: '#6b4f2a',
                },
              {
                  x: 0.05,
                  y: 0.05,
                  z: 0.18,
                  L: 1.9,
                  W: 1.7,
                  H: 0.2,
                  shape: 'box',
                  color: '#d8b87a',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.18,
                  L: 0.08,
                  W: 1.8,
                  H: 0.5,
                  shape: 'box',
                  color: '#6b4f2a',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 2,
                  W: 0.06,
                  H: 0.18,
                  shape: 'box',
                  color: '#6b4f2a',
                },
            ],
          },
        {
            id: genId(),
            name: '床头柜',
            x: 0.9498614157670244,
            y: 5.6,
            z: 0,
            L: 0.4,
            W: 0.4,
            H: 0.5,
            color: '#6a4a30',
            shape: 'box',
            doorHoles: [],
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.4,
                  W: 0.4,
                  H: 0.025,
                  shape: 'box',
                  color: '#523823',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.475,
                  L: 0.4,
                  W: 0.4,
                  H: 0.025,
                  shape: 'box',
                  color: '#523823',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.025,
                  L: 0.025,
                  W: 0.4,
                  H: 0.45,
                  shape: 'box',
                  color: '#523823',
                },
              {
                  x: 0.375,
                  y: 0,
                  z: 0.025,
                  L: 0.025,
                  W: 0.4,
                  H: 0.45,
                  shape: 'box',
                  color: '#523823',
                },
              {
                  x: 0.025,
                  y: 0.375,
                  z: 0.025,
                  L: 0.35000000000000003,
                  W: 0.025,
                  H: 0.45,
                  shape: 'box',
                  color: '#523823',
                },
              {
                  x: 0.025,
                  y: 0,
                  z: 0.245,
                  L: 0.35000000000000003,
                  W: 0.025,
                  H: 0.23,
                  shape: 'box',
                  color: '#6a4a30',
                },
            ],
          },
        {
            id: genId(),
            name: '床头柜',
            x: 3.2135845831449696,
            y: 5.6,
            z: 0,
            L: 0.4,
            W: 0.4,
            H: 0.5,
            color: '#6a4a30',
            shape: 'box',
            doorHoles: [],
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.4,
                  W: 0.4,
                  H: 0.025,
                  shape: 'box',
                  color: '#523823',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.475,
                  L: 0.4,
                  W: 0.4,
                  H: 0.025,
                  shape: 'box',
                  color: '#523823',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.025,
                  L: 0.025,
                  W: 0.4,
                  H: 0.45,
                  shape: 'box',
                  color: '#523823',
                },
              {
                  x: 0.375,
                  y: 0,
                  z: 0.025,
                  L: 0.025,
                  W: 0.4,
                  H: 0.45,
                  shape: 'box',
                  color: '#523823',
                },
              {
                  x: 0.025,
                  y: 0.375,
                  z: 0.025,
                  L: 0.35000000000000003,
                  W: 0.025,
                  H: 0.45,
                  shape: 'box',
                  color: '#523823',
                },
              {
                  x: 0.025,
                  y: 0,
                  z: 0.245,
                  L: 0.35000000000000003,
                  W: 0.025,
                  H: 0.23,
                  shape: 'box',
                  color: '#6a4a30',
                },
            ],
          },
        {
            id: genId(),
            name: '茶几',
            x: 5.1330171091695025,
            y: 4.1255018175382405,
            z: 0,
            L: 1,
            W: 0.5,
            H: 0.4,
            color: '#8b4513',
            shape: 'box',
            doorHoles: [],
            rotZ: 1.5707963267948966,
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0.365,
                  L: 1,
                  W: 0.5,
                  H: 0.035,
                  shape: 'box',
                  color: '#6b3410',
                },
              {
                  x: 0.05,
                  y: 0.05,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.365,
                  shape: 'box',
                  color: '#6b3410',
                },
              {
                  x: 0.8999999999999999,
                  y: 0.05,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.365,
                  shape: 'box',
                  color: '#6b3410',
                },
              {
                  x: 0.05,
                  y: 0.4,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.365,
                  shape: 'box',
                  color: '#6b3410',
                },
              {
                  x: 0.8999999999999999,
                  y: 0.4,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.365,
                  shape: 'box',
                  color: '#6b3410',
                },
            ],
          },
        {
            id: genId(),
            name: '客厅窗户',
            x: 4.8883442923858,
            y: 5.949999999999999,
            z: 0.8546743969331103,
            L: 1.6,
            W: 0.05,
            H: 1.4,
            color: '#7dd3fc',
            shape: 'box',
            doorHoles: [],
            category: 'wall',
            isWindow: true,
            asHeatSource: true,
            windowTemp: 35,
          },
        {
            id: genId(),
            name: '窗户',
            x: 8.475,
            y: 4.040650226760683,
            z: 1.43442493973981,
            L: 3,
            W: 0.05,
            H: 1,
            color: '#7dd3fc',
            shape: 'box',
            doorHoles: [],
            rotZ: 1.5707963267948966,
            category: 'wall',
            isWindow: true,
            asHeatSource: true,
            windowTemp: 35,
          },
        {
            id: genId(),
            name: '卧室窗户',
            x: -0.775,
            y: 3.935582070345491,
            z: 0.842650013746459,
            L: 1.6,
            W: 0.05,
            H: 1.4,
            color: '#7dd3fc',
            shape: 'box',
            doorHoles: [],
            rotZ: 1.5707963267948966,
            category: 'wall',
            isWindow: true,
            asHeatSource: true,
            windowTemp: 35,
          },
        {
            id: genId(),
            name: '厨房地柜',
            x: 0,
            y: 0,
            z: 0,
            L: 2,
            W: 0.6,
            H: 0.85,
            color: '#4a5d4f',
            shape: 'box',
            doorHoles: [],
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 2,
                  W: 0.6,
                  H: 0.03,
                  shape: 'box',
                  color: '#3a4a3e',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.82,
                  L: 2,
                  W: 0.6,
                  H: 0.03,
                  shape: 'box',
                  color: '#3a4a3e',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.03,
                  L: 0.03,
                  W: 0.6,
                  H: 0.79,
                  shape: 'box',
                  color: '#3a4a3e',
                },
              {
                  x: 1.97,
                  y: 0,
                  z: 0.03,
                  L: 0.03,
                  W: 0.6,
                  H: 0.79,
                  shape: 'box',
                  color: '#3a4a3e',
                },
              {
                  x: 0.03,
                  y: 0.57,
                  z: 0.03,
                  L: 1.94,
                  W: 0.03,
                  H: 0.79,
                  shape: 'box',
                  color: '#3a4a3e',
                },
              {
                  x: 0.03,
                  y: 0,
                  z: 0.03,
                  L: 0.96,
                  W: 0.03,
                  H: 0.79,
                  shape: 'box',
                  color: '#4a5d4f',
                },
              {
                  x: 1.01,
                  y: 0,
                  z: 0.03,
                  L: 0.96,
                  W: 0.03,
                  H: 0.79,
                  shape: 'box',
                  color: '#4a5d4f',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.85,
                  L: 2,
                  W: 0.6,
                  H: 0.04,
                  shape: 'box',
                  color: '#3a3a3a',
                },
            ],
          },
        {
            id: genId(),
            name: '高橱柜',
            x: 1.9965377491845653,
            y: 0,
            z: 0,
            L: 0.6,
            W: 0.6,
            H: 1.9,
            color: '#45594b',
            shape: 'box',
            doorHoles: [],
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.6,
                  W: 0.6,
                  H: 0.03,
                  shape: 'box',
                  color: '#364438',
                },
              {
                  x: 0,
                  y: 0,
                  z: 1.8699999999999999,
                  L: 0.6,
                  W: 0.6,
                  H: 0.03,
                  shape: 'box',
                  color: '#364438',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.03,
                  L: 0.03,
                  W: 0.6,
                  H: 1.8399999999999999,
                  shape: 'box',
                  color: '#364438',
                },
              {
                  x: 0.57,
                  y: 0,
                  z: 0.03,
                  L: 0.03,
                  W: 0.6,
                  H: 1.8399999999999999,
                  shape: 'box',
                  color: '#364438',
                },
              {
                  x: 0.03,
                  y: 0.57,
                  z: 0.03,
                  L: 0.54,
                  W: 0.03,
                  H: 1.8399999999999999,
                  shape: 'box',
                  color: '#364438',
                },
              {
                  x: 0.03,
                  y: 0,
                  z: 0.03,
                  L: 0.54,
                  W: 0.03,
                  H: 0.9099999999999999,
                  shape: 'box',
                  color: '#45594b',
                },
              {
                  x: 0.03,
                  y: 0,
                  z: 0.96,
                  L: 0.54,
                  W: 0.03,
                  H: 0.9099999999999999,
                  shape: 'box',
                  color: '#45594b',
                },
            ],
          },
        {
            id: genId(),
            name: '厨房窗户',
            x: -0.475,
            y: 1.1734390407260191,
            z: 1,
            L: 1,
            W: 0.05,
            H: 1.2,
            color: '#7dd3fc',
            shape: 'box',
            doorHoles: [],
            rotZ: 1.5707963267948966,
            category: 'wall',
            isWindow: true,
            asHeatSource: true,
            windowTemp: 35,
          },
        {
            id: genId(),
            name: '书柜',
            x: 9.200000000000001,
            y: 1.6139034985050191,
            z: 0,
            L: 0.4,
            W: 1.2,
            H: 1.8,
            color: '#6b4226',
            shape: 'box',
            doorHoles: [],
            rotZ: 4.71238898038469,
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.4,
                  W: 1.2,
                  H: 0.03,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 0,
                  z: 1.77,
                  L: 0.4,
                  W: 1.2,
                  H: 0.03,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.03,
                  L: 0.4,
                  W: 0.03,
                  H: 1.74,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 1.17,
                  z: 0.03,
                  L: 0.4,
                  W: 0.03,
                  H: 1.74,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.03,
                  L: 0.03,
                  W: 1.2,
                  H: 1.74,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0.03,
                  y: 0.03,
                  z: 0.435,
                  L: 0.34,
                  W: 1.14,
                  H: 0.03,
                  shape: 'box',
                  color: '#6b4226',
                },
              {
                  x: 0.03,
                  y: 0.03,
                  z: 0.885,
                  L: 0.34,
                  W: 1.14,
                  H: 0.03,
                  shape: 'box',
                  color: '#6b4226',
                },
              {
                  x: 0.03,
                  y: 0.03,
                  z: 1.3350000000000002,
                  L: 0.34,
                  W: 1.14,
                  H: 0.03,
                  shape: 'box',
                  color: '#6b4226',
                },
            ],
          },
      ],
      vents: [],
      heatSources: [],
      devices: [
        {
            id: genId(),
            deviceId: 'ac-wall-gree-1.5hp',
            name: '壁挂式空调 1.5匹',
            brand: '格力',
            category: 'air_conditioner',
            position: {
              x: 3.580769805040587,
              y: 4.9411981011504835,
              z: 2.022797497122828,
            },
            geometry: {
              length: 0.85,
              width: 0.3,
              height: 0.28,
            },
            bodyParts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.85,
                  W: 0.3,
                  H: 0.28,
                  shape: 'box',
                  color: '#e2e8f0',
                },
              {
                  x: 0,
                  y: 0.26,
                  z: 0.02,
                  L: 0.85,
                  W: 0.04,
                  H: 0.24000000000000002,
                  shape: 'box',
                  color: '#cbd5e1',
                },
              {
                  x: 0.02,
                  y: 0.24,
                  z: 0,
                  L: 0.8099999999999999,
                  W: 0.06,
                  H: 0.05,
                  shape: 'box',
                  color: '#94a3b8',
                },
            ],
            modeIndex: 0,
            outlets: [
              {
                  id: genId(),
                  name: '出风口',
                  relativePosition: [
                    0.425,
                    0.02,
                    0.02,
                  ],
                  size: [
                    0.6,
                    0.04,
                    0.04,
                  ],
                  velocity: [
                    0,
                    -2.25,
                    -0.625,
                  ],
                  temperature: 16,
                  swing: {
                    enabled: true,
                    mode: 'vertical',
                    amplitude: 0.5235987755982988,
                    period: 10,
                  },
                },
            ],
            inlets: [
              {
                  id: genId(),
                  name: '回风口',
                  relativePosition: [
                    0.425,
                    0.15,
                    0.27,
                  ],
                  size: [
                    0.5,
                    0.2,
                    0.02,
                  ],
                  mode: 'velocity',
                  velocity: [
                    0,
                    0,
                    -0.6,
                  ],
                  temperature: 25,
                },
            ],
            rotZ: 4.71238898038469,
            color: '#60a5fa',
          },
        {
            id: genId(),
            deviceId: 'tv-55inch',
            name: '液晶电视 55寸',
            brand: '小米',
            category: 'tv',
            position: {
              x: 6.755129922393273,
              y: 4.615503955826703,
              z: 0.895269966609969,
            },
            geometry: {
              length: 1.23,
              width: 0.08,
              height: 0.72,
            },
            bodyParts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 1.23,
                  W: 0.08,
                  H: 0.72,
                  shape: 'box',
                  color: '#0f172a',
                },
              {
                  x: 0.03,
                  y: 0,
                  z: 0.03,
                  L: 1.17,
                  W: 0.08,
                  H: 0.6599999999999999,
                  shape: 'box',
                  color: '#1e293b',
                },
              {
                  x: 0.46499999999999997,
                  y: 0,
                  z: -0.04,
                  L: 0.3,
                  W: 0.1,
                  H: 0.04,
                  shape: 'box',
                  color: '#334155',
                },
            ],
            modeIndex: 0,
            outlets: [],
            inlets: [],
            heatSourceId: 'item_74335',
            heatTemp: 36,
            rotZ: 1.5707963267948966,
            color: '#1e293b',
          },
        {
            id: genId(),
            deviceId: 'ac-wall-gree-1.5hp',
            name: '壁挂式空调 1.5匹',
            brand: '格力',
            category: 'air_conditioner',
            position: {
              x: 7.7777351846660805,
              y: 5.699999999999999,
              z: 2.03041383652016,
            },
            geometry: {
              length: 0.85,
              width: 0.3,
              height: 0.28,
            },
            bodyParts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.85,
                  W: 0.3,
                  H: 0.28,
                  shape: 'box',
                  color: '#e2e8f0',
                },
              {
                  x: 0,
                  y: 0.26,
                  z: 0.02,
                  L: 0.85,
                  W: 0.04,
                  H: 0.24000000000000002,
                  shape: 'box',
                  color: '#cbd5e1',
                },
              {
                  x: 0.02,
                  y: 0.24,
                  z: 0,
                  L: 0.8099999999999999,
                  W: 0.06,
                  H: 0.05,
                  shape: 'box',
                  color: '#94a3b8',
                },
            ],
            modeIndex: 0,
            outlets: [
              {
                  id: genId(),
                  name: '出风口',
                  relativePosition: [
                    0.425,
                    0.02,
                    0.02,
                  ],
                  size: [
                    0.6,
                    0.04,
                    0.04,
                  ],
                  velocity: [
                    0,
                    -2.25,
                    -0.625,
                  ],
                  temperature: 16,
                  swing: {
                    enabled: true,
                    mode: 'vertical',
                    amplitude: 0.5235987755982988,
                    period: 10,
                  },
                },
            ],
            inlets: [
              {
                  id: genId(),
                  name: '回风口',
                  relativePosition: [
                    0.425,
                    0.15,
                    0.27,
                  ],
                  size: [
                    0.5,
                    0.2,
                    0.02,
                  ],
                  mode: 'velocity',
                  velocity: [
                    0,
                    0,
                    -0.6,
                  ],
                  temperature: 25,
                },
            ],
            color: '#60a5fa',
          },
        {
            id: genId(),
            deviceId: 'ac-wall-gree-1.5hp',
            name: '壁挂式空调 1.5匹',
            brand: '格力',
            category: 'air_conditioner',
            position: {
              x: 2.337869071461683,
              y: 5.699999999999999,
              z: 2.015484917435024,
            },
            geometry: {
              length: 0.85,
              width: 0.3,
              height: 0.28,
            },
            bodyParts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.85,
                  W: 0.3,
                  H: 0.28,
                  shape: 'box',
                  color: '#e2e8f0',
                },
              {
                  x: 0,
                  y: 0.26,
                  z: 0.02,
                  L: 0.85,
                  W: 0.04,
                  H: 0.24000000000000002,
                  shape: 'box',
                  color: '#cbd5e1',
                },
              {
                  x: 0.02,
                  y: 0.24,
                  z: 0,
                  L: 0.8099999999999999,
                  W: 0.06,
                  H: 0.05,
                  shape: 'box',
                  color: '#94a3b8',
                },
            ],
            modeIndex: 0,
            outlets: [
              {
                  id: genId(),
                  name: '出风口',
                  relativePosition: [
                    0.425,
                    0.02,
                    0.02,
                  ],
                  size: [
                    0.6,
                    0.04,
                    0.04,
                  ],
                  velocity: [
                    0,
                    -2.25,
                    -0.625,
                  ],
                  temperature: 16,
                  swing: {
                    enabled: true,
                    mode: 'vertical',
                    amplitude: 0.5235987755982988,
                    period: 10,
                  },
                },
            ],
            inlets: [
              {
                  id: genId(),
                  name: '回风口',
                  relativePosition: [
                    0.425,
                    0.15,
                    0.27,
                  ],
                  size: [
                    0.5,
                    0.2,
                    0.02,
                  ],
                  mode: 'velocity',
                  velocity: [
                    0,
                    0,
                    -0.6,
                  ],
                  temperature: 25,
                },
            ],
            color: '#60a5fa',
          },
        {
            id: genId(),
            deviceId: 'range-hood-90cm',
            name: '侧吸式油烟机 90cm',
            brand: '方太',
            category: 'range_hood',
            position: {
              x: 0.6269813784680907,
              y: 1.3877787807814457e-16,
              z: 1.2747751790981376,
            },
            geometry: {
              length: 0.9,
              width: 0.45,
              height: 0.6,
            },
            bodyParts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.9,
                  W: 0.45,
                  H: 0.6,
                  shape: 'prism_y',
                  color: '#9ca3af',
                },
              {
                  x: 0,
                  y: 0.29000000000000004,
                  z: 0.5,
                  L: 0.9,
                  W: 0.16,
                  H: 0.1,
                  shape: 'box',
                  color: '#6b7280',
                },
            ],
            modeIndex: 0,
            outlets: [],
            inlets: [
              {
                  id: genId(),
                  name: '吸烟口',
                  relativePosition: [
                    0.45,
                    0.4,
                    0.04,
                  ],
                  size: [
                    0.8,
                    0.04,
                    0.1,
                  ],
                  mode: 'velocity',
                  velocity: [
                    0,
                    2,
                    0,
                  ],
                  temperature: 30,
                },
            ],
            rotZ: 3.141592653589793,
            color: '#64748b',
          },
        {
            id: genId(),
            deviceId: 'exhaust-fan-ceil-30cm',
            name: '吸顶换气扇 30cm',
            brand: '绿岛风',
            category: 'exhaust_fan',
            position: {
              x: 5.914212228479291,
              y: 0.7625628405877788,
              z: 2.3,
            },
            geometry: {
              length: 0.32,
              width: 0.32,
              height: 0.2,
            },
            bodyParts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.32,
                  W: 0.32,
                  H: 0.06,
                  shape: 'box',
                  color: '#e5e7eb',
                },
              {
                  x: 0.04,
                  y: 0.04,
                  z: 0.06,
                  L: 0.24,
                  W: 0.24,
                  H: 0.14,
                  shape: 'box',
                  color: '#9ca3af',
                },
              {
                  x: 0.06,
                  y: 0.06,
                  z: 0,
                  L: 0.2,
                  W: 0.02,
                  H: 0.2,
                  shape: 'box',
                  color: '#6b7280',
                },
            ],
            modeIndex: 0,
            outlets: [],
            inlets: [
              {
                  id: genId(),
                  name: '排气口',
                  relativePosition: [
                    0.16,
                    0.16,
                    0,
                  ],
                  size: [
                    0.26,
                    0.26,
                    0.02,
                  ],
                  mode: 'velocity',
                  velocity: [
                    0,
                    0,
                    1,
                  ],
                  temperature: 30,
                },
            ],
            color: '#94a3b8',
          },
      ],
    };
}

/* ============================================================
 * 样本：办公室 · 双柜机空调
 * 中型办公室，两台柜式空调分区制冷
 * 房间 ：office
 * ============================================================ */
function officeCabinetAcRoom(): RoomLayout {
  return {
      length: 8,
      width: 8,
      height: 3.5,
      boxes: [
        {
            id: genId(),
            name: '书柜',
            x: 0,
            y: 6.024347632827464,
            z: 0,
            L: 0.4,
            W: 1.2,
            H: 1.8,
            color: '#6b4226',
            shape: 'box',
            doorHoles: [],
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.4,
                  W: 1.2,
                  H: 0.03,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 0,
                  z: 1.77,
                  L: 0.4,
                  W: 1.2,
                  H: 0.03,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.03,
                  L: 0.4,
                  W: 0.03,
                  H: 1.74,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 1.17,
                  z: 0.03,
                  L: 0.4,
                  W: 0.03,
                  H: 1.74,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.03,
                  L: 0.03,
                  W: 1.2,
                  H: 1.74,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0.03,
                  y: 0.03,
                  z: 0.435,
                  L: 0.34,
                  W: 1.14,
                  H: 0.03,
                  shape: 'box',
                  color: '#6b4226',
                },
              {
                  x: 0.03,
                  y: 0.03,
                  z: 0.885,
                  L: 0.34,
                  W: 1.14,
                  H: 0.03,
                  shape: 'box',
                  color: '#6b4226',
                },
              {
                  x: 0.03,
                  y: 0.03,
                  z: 1.3350000000000002,
                  L: 0.34,
                  W: 1.14,
                  H: 0.03,
                  shape: 'box',
                  color: '#6b4226',
                },
            ],
          },
        {
            id: genId(),
            name: '双人学习桌',
            x: 1.5,
            y: 5.3,
            z: 0,
            L: 2,
            W: 0.6,
            H: 0.75,
            color: '#6e5638',
            shape: 'box',
            doorHoles: [],
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0.71,
                  L: 2,
                  W: 0.6,
                  H: 0.04,
                  shape: 'box',
                  color: '#54402a',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.04,
                  W: 0.6,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 1.96,
                  y: 0,
                  z: 0,
                  L: 0.04,
                  W: 0.6,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.975,
                  y: 0.05,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.975,
                  y: 0.49999999999999994,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.08,
                  y: 0.33999999999999997,
                  z: 0.05,
                  L: 0.5,
                  W: 0.26,
                  H: 0.45,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 1.42,
                  y: 0.33999999999999997,
                  z: 0.05,
                  L: 0.5,
                  W: 0.26,
                  H: 0.45,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.99,
                  y: 0.04,
                  z: 0.45999999999999996,
                  L: 0.02,
                  W: 0.52,
                  H: 0.25,
                  shape: 'box',
                  color: '#42331f',
                },
            ],
          },
        {
            id: genId(),
            name: '双人学习桌',
            x: 1.5,
            y: 5.9,
            z: 0,
            L: 2,
            W: 0.6,
            H: 0.75,
            color: '#6e5638',
            shape: 'box',
            doorHoles: [],
            rotZ: 3.141592653589793,
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0.71,
                  L: 2,
                  W: 0.6,
                  H: 0.04,
                  shape: 'box',
                  color: '#54402a',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.04,
                  W: 0.6,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 1.96,
                  y: 0,
                  z: 0,
                  L: 0.04,
                  W: 0.6,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.975,
                  y: 0.05,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.975,
                  y: 0.49999999999999994,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.08,
                  y: 0.33999999999999997,
                  z: 0.05,
                  L: 0.5,
                  W: 0.26,
                  H: 0.45,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 1.42,
                  y: 0.33999999999999997,
                  z: 0.05,
                  L: 0.5,
                  W: 0.26,
                  H: 0.45,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.99,
                  y: 0.04,
                  z: 0.45999999999999996,
                  L: 0.02,
                  W: 0.52,
                  H: 0.25,
                  shape: 'box',
                  color: '#42331f',
                },
            ],
          },
        {
            id: genId(),
            name: '双人学习桌',
            x: 1.5,
            y: 1.5,
            z: 0,
            L: 2,
            W: 0.6,
            H: 0.75,
            color: '#6e5638',
            shape: 'box',
            doorHoles: [],
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0.71,
                  L: 2,
                  W: 0.6,
                  H: 0.04,
                  shape: 'box',
                  color: '#54402a',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.04,
                  W: 0.6,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 1.96,
                  y: 0,
                  z: 0,
                  L: 0.04,
                  W: 0.6,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.975,
                  y: 0.05,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.975,
                  y: 0.49999999999999994,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.08,
                  y: 0.33999999999999997,
                  z: 0.05,
                  L: 0.5,
                  W: 0.26,
                  H: 0.45,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 1.42,
                  y: 0.33999999999999997,
                  z: 0.05,
                  L: 0.5,
                  W: 0.26,
                  H: 0.45,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.99,
                  y: 0.04,
                  z: 0.45999999999999996,
                  L: 0.02,
                  W: 0.52,
                  H: 0.25,
                  shape: 'box',
                  color: '#42331f',
                },
            ],
          },
        {
            id: genId(),
            name: '双人学习桌',
            x: 1.5,
            y: 2.1,
            z: 0,
            L: 2,
            W: 0.6,
            H: 0.75,
            color: '#6e5638',
            shape: 'box',
            doorHoles: [],
            rotZ: 3.141592653589793,
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0.71,
                  L: 2,
                  W: 0.6,
                  H: 0.04,
                  shape: 'box',
                  color: '#54402a',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.04,
                  W: 0.6,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 1.96,
                  y: 0,
                  z: 0,
                  L: 0.04,
                  W: 0.6,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.975,
                  y: 0.05,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.975,
                  y: 0.49999999999999994,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.08,
                  y: 0.33999999999999997,
                  z: 0.05,
                  L: 0.5,
                  W: 0.26,
                  H: 0.45,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 1.42,
                  y: 0.33999999999999997,
                  z: 0.05,
                  L: 0.5,
                  W: 0.26,
                  H: 0.45,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.99,
                  y: 0.04,
                  z: 0.45999999999999996,
                  L: 0.02,
                  W: 0.52,
                  H: 0.25,
                  shape: 'box',
                  color: '#42331f',
                },
            ],
          },
        {
            id: genId(),
            name: '双人学习桌',
            x: 5,
            y: 5.3,
            z: 0,
            L: 2,
            W: 0.6,
            H: 0.75,
            color: '#6e5638',
            shape: 'box',
            doorHoles: [],
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0.71,
                  L: 2,
                  W: 0.6,
                  H: 0.04,
                  shape: 'box',
                  color: '#54402a',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.04,
                  W: 0.6,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 1.96,
                  y: 0,
                  z: 0,
                  L: 0.04,
                  W: 0.6,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.975,
                  y: 0.05,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.975,
                  y: 0.49999999999999994,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.08,
                  y: 0.33999999999999997,
                  z: 0.05,
                  L: 0.5,
                  W: 0.26,
                  H: 0.45,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 1.42,
                  y: 0.33999999999999997,
                  z: 0.05,
                  L: 0.5,
                  W: 0.26,
                  H: 0.45,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.99,
                  y: 0.04,
                  z: 0.45999999999999996,
                  L: 0.02,
                  W: 0.52,
                  H: 0.25,
                  shape: 'box',
                  color: '#42331f',
                },
            ],
          },
        {
            id: genId(),
            name: '双人学习桌',
            x: 5,
            y: 5.9,
            z: 0,
            L: 2,
            W: 0.6,
            H: 0.75,
            color: '#6e5638',
            shape: 'box',
            doorHoles: [],
            rotZ: 3.141592653589793,
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0.71,
                  L: 2,
                  W: 0.6,
                  H: 0.04,
                  shape: 'box',
                  color: '#54402a',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.04,
                  W: 0.6,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 1.96,
                  y: 0,
                  z: 0,
                  L: 0.04,
                  W: 0.6,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.975,
                  y: 0.05,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.975,
                  y: 0.49999999999999994,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.08,
                  y: 0.33999999999999997,
                  z: 0.05,
                  L: 0.5,
                  W: 0.26,
                  H: 0.45,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 1.42,
                  y: 0.33999999999999997,
                  z: 0.05,
                  L: 0.5,
                  W: 0.26,
                  H: 0.45,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.99,
                  y: 0.04,
                  z: 0.45999999999999996,
                  L: 0.02,
                  W: 0.52,
                  H: 0.25,
                  shape: 'box',
                  color: '#42331f',
                },
            ],
          },
        {
            id: genId(),
            name: '双人学习桌',
            x: 5,
            y: 1.5,
            z: 0,
            L: 2,
            W: 0.6,
            H: 0.75,
            color: '#6e5638',
            shape: 'box',
            doorHoles: [],
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0.71,
                  L: 2,
                  W: 0.6,
                  H: 0.04,
                  shape: 'box',
                  color: '#54402a',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.04,
                  W: 0.6,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 1.96,
                  y: 0,
                  z: 0,
                  L: 0.04,
                  W: 0.6,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.975,
                  y: 0.05,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.975,
                  y: 0.49999999999999994,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.08,
                  y: 0.33999999999999997,
                  z: 0.05,
                  L: 0.5,
                  W: 0.26,
                  H: 0.45,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 1.42,
                  y: 0.33999999999999997,
                  z: 0.05,
                  L: 0.5,
                  W: 0.26,
                  H: 0.45,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.99,
                  y: 0.04,
                  z: 0.45999999999999996,
                  L: 0.02,
                  W: 0.52,
                  H: 0.25,
                  shape: 'box',
                  color: '#42331f',
                },
            ],
          },
        {
            id: genId(),
            name: '双人学习桌',
            x: 5,
            y: 2.1,
            z: 0,
            L: 2,
            W: 0.6,
            H: 0.75,
            color: '#6e5638',
            shape: 'box',
            doorHoles: [],
            rotZ: 3.141592653589793,
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0.71,
                  L: 2,
                  W: 0.6,
                  H: 0.04,
                  shape: 'box',
                  color: '#54402a',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.04,
                  W: 0.6,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 1.96,
                  y: 0,
                  z: 0,
                  L: 0.04,
                  W: 0.6,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.975,
                  y: 0.05,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.975,
                  y: 0.49999999999999994,
                  z: 0,
                  L: 0.05,
                  W: 0.05,
                  H: 0.71,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.08,
                  y: 0.33999999999999997,
                  z: 0.05,
                  L: 0.5,
                  W: 0.26,
                  H: 0.45,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 1.42,
                  y: 0.33999999999999997,
                  z: 0.05,
                  L: 0.5,
                  W: 0.26,
                  H: 0.45,
                  shape: 'box',
                  color: '#42331f',
                },
              {
                  x: 0.99,
                  y: 0.04,
                  z: 0.45999999999999996,
                  L: 0.02,
                  W: 0.52,
                  H: 0.25,
                  shape: 'box',
                  color: '#42331f',
                },
            ],
          },
        {
            id: genId(),
            name: '窗户',
            x: 6.5,
            y: 7.949999999999999,
            z: 1,
            L: 1,
            W: 0.05,
            H: 1.4,
            color: '#7dd3fc',
            shape: 'box',
            doorHoles: [],
            category: 'wall',
            isWindow: true,
            windowTemp: 35,
          },
        {
            id: genId(),
            name: '窗户',
            x: 4.5,
            y: 7.949999999999999,
            z: 1,
            L: 1,
            W: 0.05,
            H: 1.4,
            color: '#7dd3fc',
            shape: 'box',
            doorHoles: [],
            category: 'wall',
            isWindow: true,
            windowTemp: 35,
          },
        {
            id: genId(),
            name: '窗户',
            x: 2.5,
            y: 7.949999999999999,
            z: 1,
            L: 1,
            W: 0.05,
            H: 1.4,
            color: '#7dd3fc',
            shape: 'box',
            doorHoles: [],
            category: 'wall',
            isWindow: true,
            windowTemp: 35,
          },
        {
            id: genId(),
            name: '窗户',
            x: 0.5,
            y: 7.949999999999999,
            z: 1,
            L: 1,
            W: 0.05,
            H: 1.4,
            color: '#7dd3fc',
            shape: 'box',
            doorHoles: [],
            category: 'wall',
            isWindow: true,
            windowTemp: 35,
          },
        {
            id: genId(),
            name: '书柜',
            x: 0,
            y: 4.278535787739397,
            z: 0,
            L: 0.4,
            W: 1.2,
            H: 1.8,
            color: '#6b4226',
            shape: 'box',
            doorHoles: [],
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.4,
                  W: 1.2,
                  H: 0.03,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 0,
                  z: 1.77,
                  L: 0.4,
                  W: 1.2,
                  H: 0.03,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.03,
                  L: 0.4,
                  W: 0.03,
                  H: 1.74,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 1.17,
                  z: 0.03,
                  L: 0.4,
                  W: 0.03,
                  H: 1.74,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.03,
                  L: 0.03,
                  W: 1.2,
                  H: 1.74,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0.03,
                  y: 0.03,
                  z: 0.435,
                  L: 0.34,
                  W: 1.14,
                  H: 0.03,
                  shape: 'box',
                  color: '#6b4226',
                },
              {
                  x: 0.03,
                  y: 0.03,
                  z: 0.885,
                  L: 0.34,
                  W: 1.14,
                  H: 0.03,
                  shape: 'box',
                  color: '#6b4226',
                },
              {
                  x: 0.03,
                  y: 0.03,
                  z: 1.3350000000000002,
                  L: 0.34,
                  W: 1.14,
                  H: 0.03,
                  shape: 'box',
                  color: '#6b4226',
                },
            ],
          },
        {
            id: genId(),
            name: '书柜',
            x: 0,
            y: 0.9915499968808846,
            z: 0,
            L: 0.4,
            W: 1.2,
            H: 1.8,
            color: '#6b4226',
            shape: 'box',
            doorHoles: [],
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.4,
                  W: 1.2,
                  H: 0.03,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 0,
                  z: 1.77,
                  L: 0.4,
                  W: 1.2,
                  H: 0.03,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.03,
                  L: 0.4,
                  W: 0.03,
                  H: 1.74,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 1.17,
                  z: 0.03,
                  L: 0.4,
                  W: 0.03,
                  H: 1.74,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.03,
                  L: 0.03,
                  W: 1.2,
                  H: 1.74,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0.03,
                  y: 0.03,
                  z: 0.435,
                  L: 0.34,
                  W: 1.14,
                  H: 0.03,
                  shape: 'box',
                  color: '#6b4226',
                },
              {
                  x: 0.03,
                  y: 0.03,
                  z: 0.885,
                  L: 0.34,
                  W: 1.14,
                  H: 0.03,
                  shape: 'box',
                  color: '#6b4226',
                },
              {
                  x: 0.03,
                  y: 0.03,
                  z: 1.3350000000000002,
                  L: 0.34,
                  W: 1.14,
                  H: 0.03,
                  shape: 'box',
                  color: '#6b4226',
                },
            ],
          },
        {
            id: genId(),
            name: '书柜',
            x: 0,
            y: 2.6147568697887045,
            z: 0,
            L: 0.4,
            W: 1.2,
            H: 1.8,
            color: '#6b4226',
            shape: 'box',
            doorHoles: [],
            category: 'furniture',
            parts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.4,
                  W: 1.2,
                  H: 0.03,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 0,
                  z: 1.77,
                  L: 0.4,
                  W: 1.2,
                  H: 0.03,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.03,
                  L: 0.4,
                  W: 0.03,
                  H: 1.74,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 1.17,
                  z: 0.03,
                  L: 0.4,
                  W: 0.03,
                  H: 1.74,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0,
                  y: 0,
                  z: 0.03,
                  L: 0.03,
                  W: 1.2,
                  H: 1.74,
                  shape: 'box',
                  color: '#553520',
                },
              {
                  x: 0.03,
                  y: 0.03,
                  z: 0.435,
                  L: 0.34,
                  W: 1.14,
                  H: 0.03,
                  shape: 'box',
                  color: '#6b4226',
                },
              {
                  x: 0.03,
                  y: 0.03,
                  z: 0.885,
                  L: 0.34,
                  W: 1.14,
                  H: 0.03,
                  shape: 'box',
                  color: '#6b4226',
                },
              {
                  x: 0.03,
                  y: 0.03,
                  z: 1.3350000000000002,
                  L: 0.34,
                  W: 1.14,
                  H: 0.03,
                  shape: 'box',
                  color: '#6b4226',
                },
            ],
          },
      ],
      vents: [],
      heatSources: [],
      devices: [
        {
            id: genId(),
            deviceId: 'ac-cabinet-gree-3hp',
            name: '柜式空调 3匹',
            brand: '格力',
            category: 'air_conditioner',
            position: {
              x: 7.574999999999999,
              y: 3.66665720155083,
              z: 0,
            },
            geometry: {
              length: 0.5,
              width: 0.35,
              height: 1.8,
            },
            bodyParts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.5,
                  W: 0.35,
                  H: 1.8,
                  shape: 'box',
                  color: '#f1f5f9',
                },
              {
                  x: 0,
                  y: 0.31999999999999995,
                  z: 0.05,
                  L: 0.5,
                  W: 0.03,
                  H: 1.7,
                  shape: 'box',
                  color: '#cbd5e1',
                },
              {
                  x: 0.05,
                  y: 0.3,
                  z: 1.55,
                  L: 0.4,
                  W: 0.05,
                  H: 0.2,
                  shape: 'box',
                  color: '#94a3b8',
                },
              {
                  x: 0.05,
                  y: 0.3,
                  z: 0.2,
                  L: 0.4,
                  W: 0.05,
                  H: 1.1,
                  shape: 'box',
                  color: '#94a3b8',
                },
            ],
            modeIndex: 0,
            outlets: [
              {
                  id: genId(),
                  name: '出风口',
                  relativePosition: [
                    0.25,
                    0.02,
                    1.65,
                  ],
                  size: [
                    0.4,
                    0.04,
                    0.2,
                  ],
                  velocity: [
                    0,
                    -4,
                    0.1875,
                  ],
                  temperature: 15,
                  swing: {
                    enabled: true,
                    mode: 'horizontal',
                    amplitude: 0.5235987755982988,
                    period: 10,
                  },
                },
            ],
            inlets: [
              {
                  id: genId(),
                  name: '回风口',
                  relativePosition: [
                    0.25,
                    0.02,
                    0.75,
                  ],
                  size: [
                    0.35,
                    0.04,
                    0.6,
                  ],
                  mode: 'velocity',
                  velocity: [
                    0,
                    1.0799999999999998,
                    0,
                  ],
                  temperature: 25,
                },
            ],
            rotZ: 1.5707963267948966,
            color: '#60a5fa',
          },
        {
            id: genId(),
            deviceId: 'ac-cabinet-gree-3hp',
            name: '柜式空调 3匹',
            brand: '格力',
            category: 'air_conditioner',
            position: {
              x: 3.999390230612632,
              y: 1.3877787807814457e-16,
              z: 0,
            },
            geometry: {
              length: 0.5,
              width: 0.35,
              height: 1.8,
            },
            bodyParts: [
              {
                  x: 0,
                  y: 0,
                  z: 0,
                  L: 0.5,
                  W: 0.35,
                  H: 1.8,
                  shape: 'box',
                  color: '#f1f5f9',
                },
              {
                  x: 0,
                  y: 0.31999999999999995,
                  z: 0.05,
                  L: 0.5,
                  W: 0.03,
                  H: 1.7,
                  shape: 'box',
                  color: '#cbd5e1',
                },
              {
                  x: 0.05,
                  y: 0.3,
                  z: 1.55,
                  L: 0.4,
                  W: 0.05,
                  H: 0.2,
                  shape: 'box',
                  color: '#94a3b8',
                },
              {
                  x: 0.05,
                  y: 0.3,
                  z: 0.2,
                  L: 0.4,
                  W: 0.05,
                  H: 1.1,
                  shape: 'box',
                  color: '#94a3b8',
                },
            ],
            modeIndex: 0,
            outlets: [
              {
                  id: genId(),
                  name: '出风口',
                  relativePosition: [
                    0.25,
                    0.02,
                    1.65,
                  ],
                  size: [
                    0.4,
                    0.04,
                    0.2,
                  ],
                  velocity: [
                    0,
                    -4,
                    0.1875,
                  ],
                  temperature: 15,
                  swing: {
                    enabled: true,
                    mode: 'horizontal',
                    amplitude: 0.5235987755982988,
                    period: 10,
                  },
                },
            ],
            inlets: [
              {
                  id: genId(),
                  name: '回风口',
                  relativePosition: [
                    0.25,
                    0.02,
                    0.75,
                  ],
                  size: [
                    0.35,
                    0.04,
                    0.6,
                  ],
                  mode: 'velocity',
                  velocity: [
                    0,
                    1.0799999999999998,
                    0,
                  ],
                  temperature: 25,
                },
            ],
            rotZ: 3.141592653589793,
            color: '#60a5fa',
          },
      ],
    };
}

export const SAMPLE_ROOMS: SampleRoom[] = [
  {
    id: 'simple-room',
    name: '简约客厅 · 空调+电视',
    category: 'residential',
    description: '小型客厅，壁挂空调送风 + 液晶电视热源',
    tags: ['机械通风', '空调', '电视'],
    emoji: '📺',
    build: simpleRoomRoom,
  },
  {
    id: 'real-room',
    name: '实景户型 · 客厅+厨房',
    category: 'residential',
    description: '真实户型：多台空调 + 油烟机排烟 + 吸顶换气扇',
    tags: ['机械通风', '多设备', '油烟', '换气扇'],
    emoji: '🏠',
    build: realRoomRoom,
  },
  {
    id: 'office-cabinet-ac',
    name: '办公室 · 双柜机空调',
    category: 'office',
    description: '中型办公室，两台柜式空调分区制冷',
    tags: ['机械通风', '柜机空调', '大空间'],
    emoji: '🏢',
    build: officeCabinetAcRoom,
  },
];
